import type { ComponentChildren } from 'preact';
import { useState } from 'preact/hooks';
import { useDesktop } from '../components/useDesktop';
export function ReaderToolbar({ title, contentsOpen, highlightAvailable = false, highlightActive = false, highlightOpen = false, onBack, onContents, onNote, onSettings, onEngines, onHighlight, children }: { title: string; contentsOpen: boolean; highlightAvailable?: boolean; highlightActive?: boolean; highlightOpen?: boolean; onBack: () => void; onContents: () => void; onNote: () => void; onSettings: () => void; onEngines: () => void; onHighlight?: () => void; children: ComponentChildren }) {
  const desktop = useDesktop();
  const [menuOpen, setMenuOpen] = useState(false);
  return <header class="reader-header">
    <button class="icon-button" aria-label="Back to library" onClick={onBack}><svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m12 5-7 7 7 7M5 12h15" /></svg></button>
    <button class="icon-button" aria-label="Contents" aria-expanded={contentsOpen} onClick={onContents}><svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16" /></svg></button>
    <h1>{title}</h1><div class="reader-header-position">{children}</div>
    {desktop ? <><button class="text-button" onClick={onNote} aria-label="Document notes">Note</button><button class="text-button" onClick={onSettings} aria-label="Reader settings">Aa</button><button class="icon-button" onClick={onEngines} aria-label="Language engine settings"><svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="19" cy="12" r="2"/></svg></button></> : <>{highlightAvailable && <button class={`icon-button reader-highlight-button ${highlightActive ? 'active' : ''}`} aria-label={highlightActive ? 'Highlight tool on' : 'Highlight tool off'} aria-pressed={highlightActive} aria-expanded={highlightOpen} onClick={onHighlight}><svg aria-hidden="true" width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m14.5 4.5 5 5L9 20H4v-5Z"/><path d="m12 7 5 5M4 22h7"/></svg></button>}<div class="reader-more"><button class="icon-button" aria-label="Reader menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(value => !value)}>•••</button>{menuOpen && <div class="reader-more-menu" role="menu"><button role="menuitem" onClick={() => { setMenuOpen(false); onNote(); }}>Notes</button><button role="menuitem" onClick={() => { setMenuOpen(false); onSettings(); }}>Text and theme</button><button role="menuitem" onClick={() => { setMenuOpen(false); onEngines(); }}>Language engines</button></div>}</div></>}
  </header>;
}
