import { test, expect, type Page } from '@playwright/test';
import { pdfFixture } from './pdfFixture';

test('Original mobile Click handles a real touchscreen tap without treating gestures as taps', async ({ page }) => {
  test.skip(!test.info().project.use.isMobile, 'Mobile touchscreen only');
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'click.pdf', mimeType: 'application/pdf', buffer: pdfFixture(2) });
  await page.getByRole('button', { name: 'Original', exact: true }).first().click();
  const toggle = page.getByRole('button', { name: 'Click word lookup' });
  await expect(toggle).toHaveAttribute('aria-pressed', 'true');
  const span = page.locator('.pdf-page-slot[data-pdf-page="1"] .pdf-text-layer span').filter({ hasText: 'The decision had surprised many voters.' });
  await expect(span).toBeVisible();
  const word = await span.evaluate(el => {
    const node = el.firstChild!, value = node.textContent ?? '', from = value.indexOf('decision');
    const range = document.createRange(); range.setStart(node, from); range.setEnd(node, from + 'decision'.length);
    const rect = range.getBoundingClientRect();
    return { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 };
  });
  const cdp = await page.context().newCDPSession(page);
  const start = async (x: number, y: number) => cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] });
  const finish = async () => cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const tap = async (x: number, y: number) => { await start(x, y); await finish(); };
  const sheet = page.locator('.lookup-sheet');
  const assertOverlay = async () => {
    const geometry = await page.evaluate(() => {
      const vv = window.visualViewport!;
      const card = document.querySelector('.lookup-sheet')!;
      const close = card.querySelector('[aria-label="Close meaning"]')!;
      const rect = card.getBoundingClientRect();
      const button = close.getBoundingClientRect();
      const click = document.querySelector('.pdf-click-toggle')!.getBoundingClientRect();
      return { rect: { left: rect.left, right: rect.right, top: rect.top, bottom: rect.bottom }, button: { left: button.left, right: button.right, top: button.top, bottom: button.bottom }, click: { top: click.top, bottom: click.bottom, height: click.height }, viewport: { left: vv.offsetLeft, top: vv.offsetTop, right: vv.offsetLeft + vv.width, bottom: vv.offsetTop + vv.height, scale: vv.scale }, parent: card.parentElement?.className, position: getComputedStyle(card).position, transform: getComputedStyle(card).transform };
    });
    expect(geometry.position).toBe('fixed');
    expect(geometry.rect.left).toBeGreaterThanOrEqual(geometry.viewport.left - 2);
    expect(geometry.rect.right).toBeLessThanOrEqual(geometry.viewport.right + 2);
    expect(geometry.rect.top).toBeGreaterThanOrEqual(geometry.viewport.top - 2);
    expect(geometry.rect.bottom).toBeLessThanOrEqual(geometry.viewport.bottom + 2);
    expect(geometry.button.left).toBeGreaterThanOrEqual(geometry.viewport.left);
    expect(geometry.button.right).toBeLessThanOrEqual(geometry.viewport.right);
    expect(geometry.click.height).toBeGreaterThanOrEqual(44);
    console.log('mobile overlay geometry', geometry);
  };
  const scroll = page.locator('.pdf-scroll');
  const before = await scroll.evaluate(el => el.scrollTop);
  await tap(word.x, word.y);
  await expect(sheet).toBeVisible();
  await expect(sheet).toContainText('decision');
  await assertOverlay();
  await sheet.getByRole('button', { name: 'Close meaning' }).click();
  expect(await scroll.evaluate(el => el.scrollTop)).toBe(before);
  await toggle.click();
  await expect(toggle).toHaveAttribute('aria-pressed', 'false');
  await tap(word.x, word.y);
  await expect(sheet).toBeHidden();
  await toggle.click();
  const blank = await page.locator('.pdf-page-slot[data-pdf-page="1"]').boundingBox();
  await tap(blank!.x + blank!.width - 8, blank!.y + 8);
  await expect(sheet).toBeHidden();
  const link = await page.locator('.pdf-annotation-layer a').first().boundingBox();
  await tap(link!.x + 5, link!.y + 5);
  await expect(sheet).toBeHidden();
  await start(word.x, word.y);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: word.x, y: word.y - 100 }] });
  await finish();
  await expect(sheet).toBeHidden();
  await start(word.x, word.y);
  await page.waitForTimeout(700);
  await finish();
  await expect(sheet).toBeHidden();
  const actions = page.getByRole('toolbar', { name: 'Selected text actions' });
  if (await actions.isVisible()) await actions.getByRole('button', { name: 'Close selection actions' }).click();
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: word.x, y: word.y }, { x: word.x + 40, y: word.y }] });
  await finish();
  await expect(sheet).toBeHidden();
  await scroll.evaluate(el => { el.dispatchEvent(new Event('touchmove', { bubbles: true })); el.scrollTop = 65; el.dispatchEvent(new Event('scroll')); });
  await expect(page.locator('.reader-shell')).toHaveClass(/chrome-quiet/);
  await page.evaluate(() => window.getSelection()?.removeAllRanges());
  const quietSpan = page.locator('.pdf-page-slot[data-pdf-page="1"] .pdf-text-layer span').filter({ hasText: 'Paragraph 3 on page 1' });
  const quietWord = await quietSpan.evaluate(el => {
    const node = el.firstChild!, from = (node.textContent ?? '').indexOf('Paragraph');
    const range = document.createRange(); range.setStart(node, from); range.setEnd(node, from + 'Paragraph'.length);
    const rect = range.getBoundingClientRect(); return { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 };
  });
  const topBefore = await scroll.evaluate(el => el.scrollTop);
  await tap(quietWord.x, quietWord.y);
  await expect(sheet).toBeVisible();
  await expect(sheet).toContainText('Paragraph');
  await assertOverlay();
  await sheet.getByRole('button', { name: 'Close meaning' }).click();
  expect(await scroll.evaluate(el => el.scrollTop)).toBe(topBefore);
  await page.getByRole('button', { name: 'PDF options' }).click();
  await page.getByRole('button', { name: 'Zoom in' }).click();
  await expect(sheet).toBeHidden();
  await expect(toggle).toHaveAttribute('aria-pressed', 'true');
  await scroll.evaluate(el => { el.scrollTop = 0; });
  await page.waitForTimeout(500); // PDF.js replaces the text layer asynchronously after a scale change.
  const zoomed = await span.evaluate(el => {
    const node = el.firstChild!, from = (node.textContent ?? '').indexOf('decision');
    const range = document.createRange(); range.setStart(node, from); range.setEnd(node, from + 'decision'.length);
    const rect = range.getBoundingClientRect(); return { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 };
  });
  await tap(zoomed.x, zoomed.y);
  await expect(sheet).toBeVisible();
  await expect(sheet).toContainText('decision');
  await assertOverlay();
  await cdp.send('Emulation.setPageScaleFactor', { pageScaleFactor: 1.5 });
  await expect.poll(() => page.evaluate(() => window.visualViewport?.scale)).toBeGreaterThan(1);
  await assertOverlay();
  await cdp.send('Emulation.setPageScaleFactor', { pageScaleFactor: 1 });
  await page.setViewportSize({ width: 320, height: 700 });
  await expect.poll(() => sheet.evaluate(el => el.getBoundingClientRect().width)).toBeLessThanOrEqual(322);
  await assertOverlay();
  const toolbar = await page.locator('.pdf-toolbar').boundingBox();
  const click = await toggle.boundingBox();
  expect(click!.y).toBeGreaterThanOrEqual(toolbar!.y - 1);
  expect(click!.y + click!.height).toBeLessThanOrEqual(toolbar!.y + toolbar!.height + 1);
});
