import { useDialog } from '../components/useDialog';
import type { GuideLanguage } from './store';

export const ENGLISH101_FLASHCARDS_URL = 'https://english101.hermesurf.workers.dev/viewer?id=personal-flashcards';
const copy = {
  en: { newHere:'New here?', title:'Read, save, then review', summary:'Tap a word for its meaning. Save useful vocabulary and review it later in English101.', dismiss:'Dismiss', open:'See how it works', how:'How it works', flow:'Read → Save → Review', close:'Close how Context Lens works', steps:[['Read normally','Open an article, PDF, EPUB, DOCX, or paste text.'],['Tap a word or phrase','Context Lens shows the meaning that fits the sentence.'],['Save useful vocabulary','Tap ☆ Save. The word, meaning, sentence, and source stay together.'],['Review in English101','Context Lens and English101 are separate apps. Export your vocabulary here, then import the file into Personal Flashcards.']], offlineTitle:'Use Context Lens offline', offlinePhone:'Phone: Open Context Lens online and wait for it to finish loading. Import or open your book, then add it to your Home Screen if your browser offers it. You can reopen stored books without Internet.', offlineDesktop:'Desktop: Open Context Lens online and wait for it to finish loading. Import or open your book, then install the app from Chrome or Edge if available. Open the installed app later and keep reading offline.', offlineWorks:'Works offline: reading, local dictionary, notes, highlights, and reading progress.', offlineNeeds:'Needs Internet: web results, online translation, and external providers.', transfer:'Vocabulary transfer steps', export:'Export ↓', import:'Import', cta:'Open Personal Flashcards' },
  vi: { newHere:'Bạn mới sử dụng?', title:'Đọc, lưu rồi ôn tập', summary:'Chạm vào từ để xem nghĩa. Lưu từ vựng hữu ích và ôn lại sau trong English101.', dismiss:'Bỏ qua', open:'Xem cách hoạt động', how:'Cách hoạt động', flow:'Đọc → Lưu → Ôn tập', close:'Đóng hướng dẫn Context Lens', steps:[['Đọc như bình thường','Mở bài viết, PDF, EPUB, DOCX hoặc dán văn bản.'],['Chạm vào từ hoặc cụm từ','Context Lens hiển thị nghĩa phù hợp với câu đang đọc.'],['Lưu từ vựng hữu ích','Chạm ☆ Lưu. Từ, nghĩa, câu và nguồn sẽ được lưu cùng nhau.'],['Ôn tập trong English101','Context Lens và English101 là hai ứng dụng riêng. Xuất từ vựng tại đây, rồi nhập tệp vào Personal Flashcards.']], offlineTitle:'Dùng Context Lens khi ngoại tuyến', offlinePhone:'Điện thoại: Mở Context Lens khi có mạng và đợi tải xong. Nhập hoặc mở sách, rồi thêm vào Màn hình chính nếu trình duyệt hỗ trợ. Sau đó mở lại sách đã lưu mà không cần Internet.', offlineDesktop:'Máy tính: Mở Context Lens khi có mạng và đợi tải xong. Nhập hoặc mở sách, rồi cài ứng dụng từ Chrome hoặc Edge nếu có. Mở lại ứng dụng đã cài và tiếp tục đọc ngoại tuyến.', offlineWorks:'Dùng được ngoại tuyến: đọc sách, từ điển cục bộ, ghi chú, tô sáng và tiến độ đọc.', offlineNeeds:'Cần Internet: kết quả web, dịch trực tuyến và dịch vụ bên ngoài.', transfer:'Các bước chuyển từ vựng', export:'Xuất tệp ↓', import:'Nhập tệp', cta:'Mở Personal Flashcards' }
} as const;

export function LanguageToggle({ language, onChange }: { language: GuideLanguage; onChange: (value: GuideLanguage) => void }) { return <div class="guide-language" role="group" aria-label={language === 'vi' ? 'Ngôn ngữ hướng dẫn' : 'Guide language'}><button aria-pressed={language === 'en'} onClick={() => onChange('en')}>EN</button><button aria-pressed={language === 'vi'} onClick={() => onChange('vi')}>VN</button></div>; }
export function OnboardingCard({ language, onOpen, onDismiss }: { language: GuideLanguage; onOpen: () => void; onDismiss: () => void }) { const t=copy[language]; return <aside class="onboarding-card" aria-labelledby="onboarding-card-title"><div><p class="eyebrow">{t.newHere}</p><h2 id="onboarding-card-title">{t.title}</h2><p>{t.summary}</p></div><div class="onboarding-card-actions"><button class="text-button" onClick={onDismiss}>{t.dismiss}</button><button class="secondary-button" onClick={onOpen}>{t.open}</button></div></aside>; }
export function ContextLensOnboarding({ language, onLanguageChange, onClose }: { language: GuideLanguage; onLanguageChange: (value: GuideLanguage) => void; onClose: () => void }) { const dialogRef=useDialog(onClose),t=copy[language]; return <div class="modal-layer"><button class="modal-backdrop" aria-hidden="true" tabIndex={-1} onClick={onClose}/><section ref={dialogRef} tabIndex={-1} class="settings-modal onboarding-modal" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div class="onboarding-modal-top"><LanguageToggle language={language} onChange={onLanguageChange}/><button class="icon-button close-button" onClick={onClose} aria-label={t.close}>×</button></div><header><div><p class="eyebrow">{t.how}</p><h2 id="onboarding-title">{t.flow}</h2></div></header><ol class="onboarding-steps">{t.steps.map((step,index)=><li><span aria-hidden="true">{index+1}</span><div><h3>{step[0]}</h3><p>{step[1]}</p>{index===1&&<div class="onboarding-example"><strong>indicated</strong><small>verb · showed / pointed out · cho thấy / chỉ ra</small></div>}</div></li>)}</ol><section class="guide-offline"><h3>{t.offlineTitle}</h3><p>{t.offlinePhone}</p><p>{t.offlineDesktop}</p><p>✓ {t.offlineWorks}</p><p>• {t.offlineNeeds}</p></section><div class="onboarding-transfer" aria-label={t.transfer}><strong>Context Lens</strong><span>{t.export}</span><strong>English101 Personal Flashcards</strong><span>{t.import}</span></div><a class="primary-button onboarding-cta" href={ENGLISH101_FLASHCARDS_URL} target="_blank" rel="noreferrer noopener">{t.cta}</a></section></div>; }
